name: Deploy to Remote Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Сборка Docker-образа
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag paddleforecastbot:latest

      # Шаг 3: Экспорт Docker-образа в tar-файл
      - name: Save Docker image as tar file
        run: docker save paddleforecastbot:latest -o image_paddle.tar

      # Шаг 4: Изменение прав доступа к файлу (для успешного копирования)
      - name: Set permissions on image_paddle.tar
        run: chmod 644 image_paddle.tar

      # Шаг 5: Передача tar-файла на сервер с помощью scp
      - name: Copy Docker image to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: 22
          source: "image_paddle.tar"
          target: "~/deploy/"

      # Шаг 6: Загрузка образа и запуск контейнера на удалённом сервере по SSH
      - name: Load image and run container on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: 22
          script: |
            docker load -i ~/deploy/image_paddle.tar
            docker stop paddlebot || true
            docker rm paddlebot || true
            docker run -d --name paddlebot \
              -e AI_TOKEN_POLZA="${{ secrets.AI_TOKEN_POLZA }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e TG_TOKEN="${{ secrets.TG_TOKEN }}" \
              -e WEATHER_API="${{ secrets.WEATHER_API }}" \
              paddleforecastbot:latest
